sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "my-docker"
  env: "Mydocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-449527814956"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAWRKPSDMWKW4GEEW2"
  secret_access_key: "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"