sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-992774634343"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIA6OJP2XNTQRQ26MRI"
  secret_access_key: "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"